# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fsoc < Formula
  desc "Cisco FSO Platform Developer's Control Tool"
  homepage "https://github.com/cisco-open/fsoc"
  version "0.46.0-pre2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cisco-open/fsoc/releases/download/v0.46.0-pre2/fsoc-darwin-arm64.tar.gz"
      sha256 "6e8c93faf5746c6683fe1ac4c9eb81659924c2465b3a5936c245f7aa35492b95"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cisco-open/fsoc/releases/download/v0.46.0-pre2/fsoc-darwin-amd64.tar.gz"
      sha256 "65ba4c31e6a09495533f7837e1d48668a2c6dd9d2005a0a02150b71cd8881067"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cisco-open/fsoc/releases/download/v0.46.0-pre2/fsoc-linux-arm64.tar.gz"
      sha256 "9ef527e8cee3326ce93fcf381759c994aa9455aef6ed30e775ba2d58023024d2"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cisco-open/fsoc/releases/download/v0.46.0-pre2/fsoc-linux-amd64.tar.gz"
      sha256 "4db4a0cb77fccb0d00b691212eae9b8912da315336545e5827622abeb875f7de"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
  end

  test do
    system "#{bin}/fsoc", "version"
  end
end
