# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fsoc < Formula
  desc "Cisco FSO Platform Developer's Control Tool"
  homepage "https://github.com/cisco-open/fsoc"
  version "0.47.0-pre3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cisco-open/fsoc/releases/download/v0.47.0-pre3/fsoc-darwin-amd64.tar.gz"
      sha256 "53d58f426837d7cffe6a2f19d7ee5840fb9446ba3faee5a70d8d4657ef9e908e"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cisco-open/fsoc/releases/download/v0.47.0-pre3/fsoc-darwin-arm64.tar.gz"
      sha256 "5c6c3e0528c9208904e09b533695d171c2cb84b4fdbba1de2a75c8661e34cdcb"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cisco-open/fsoc/releases/download/v0.47.0-pre3/fsoc-linux-amd64.tar.gz"
      sha256 "1d9df05234c2c4df9203f45a9ba62996552783b23fab93d1578406ab4b18daf6"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cisco-open/fsoc/releases/download/v0.47.0-pre3/fsoc-linux-arm64.tar.gz"
      sha256 "762aee05861ab77b7c963298b1dc0e4b9982d34ee0af6e46ff331487ef8a585d"

      def install
        Dir.glob("fsoc-*-*") do |f|
          bin.install f => "fsoc"
        end
      end
    end
  end

  test do
    system "#{bin}/fsoc", "version"
  end
end
